kind: Service
apiVersion: v1
metadata:
  name: sample-node-service
spec:
  type: NodePort
  selector:
    app: sample-node
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-deployment
  labels:
    app: sample-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-node
  template:
    metadata:
      labels:
        app: sample-node
    spec:
      containers:
        - name: sample-node
          image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m


